### ISSUE TITLE
enhancement for promise

### ISSUE THREAD

**Issue by zyxep** [lucasdiedrich/node-freeipa#16]
After working with this i could see that the proper way of using promises aren't being used.
So error messages goes to resolve instead of reject.

That means I can't do.
ipa.method().then().catch()

I had to manually add a simple console.log(body) in your code to debug why I sometimes couldn't execute a method.

Kinda related to #15

**Comment by lucasdiedrich** [comment]
Let me undestand, the problem is that we can't catch the error, right?

**Comment by zyxep** [comment]
The error from IPA is passed into resolve, not reject.

So my error handling isn't great.

**Comment by lucasdiedrich** [comment]
Yeap, that what i thought, my Knowledge about promises in that time was not so great, going to fix this together with the other issue. 

Another interesting question, errors provided by Freeipa we comes with an valid response, should be also warned inside catch? Because the request and the response are both valid.

**Comment by zyxep** [comment]
awesome!

**Comment by lucasdiedrich** [comment]
@zyxep , just to let you informed, since version 2.2.0 we discarded reject, everything is now resolved with erros, including the wrong login #13.
